import type { VirtualGirlfriend } from './types';

export const VIRTUAL_GIRLFRIENDS: VirtualGirlfriend[] = [
  {
    id: 'gf-1',
    name: 'Cafe Sweetheart',
    description: 'Gentle and kind, loves reading.',
    backgroundImageUrl: 'https://images.pexels.com/photos/3769021/pexels-photo-3769021.jpeg?auto=compress&cs=tinysrgb&w=600',
    prompt: 'A beautiful young woman with long brown hair, smiling gently, sitting in a cozy cafe, photorealistic, high detail',
  },
  {
    id: 'gf-2',
    name: 'Summer Meadow',
    description: 'Cheerful and bright, loves nature.',
    backgroundImageUrl: 'https://images.pexels.com/photos/1382734/pexels-photo-1382734.jpeg?auto=compress&cs=tinysrgb&w=600',
    prompt: 'A cheerful woman with short blonde hair, wearing a summer dress in a field of flowers, laughing, golden hour lighting, photorealistic',
  },
  {
    id: 'gf-3',
    name: 'Library Scholar',
    description: 'Elegant and smart, a bookworm.',
    backgroundImageUrl: 'https://images.pexels.com/photos/261856/pexels-photo-261856.jpeg?auto=compress&cs=tinysrgb&w=600',
    prompt: 'An elegant woman with black hair in a ponytail, wearing glasses and reading a book in a grand library, focused expression, soft lighting, photorealistic',
  },
  {
    id: 'gf-4',
    name: 'City Jogger',
    description: 'Sporty and energetic, an early bird.',
    backgroundImageUrl: 'https://images.pexels.com/photos/4064174/pexels-photo-4064174.jpeg?auto=compress&cs=tinysrgb&w=600',
    prompt: 'A sporty woman with red hair in a high ponytail, wearing athletic clothes, jogging in a city park at sunrise, determined look, dynamic angle, photorealistic',
  },
  {
    id: 'gf-5',
    name: 'Beach Artist',
    description: 'Creative and free-spirited.',
    backgroundImageUrl: 'https://images.pexels.com/photos/1656684/pexels-photo-1656684.jpeg?auto=compress&cs=tinysrgb&w=600',
    prompt: 'A creative woman with curly hair, wearing a flowing sundress, painting on an easel at the beach during sunset, serene and focused, photorealistic',
  },
  {
    id: 'gf-6',
    name: 'Cozy Gamer',
    description: 'Playful and fun, loves staying in.',
    backgroundImageUrl: 'https://images.pexels.com/photos/7599735/pexels-photo-7599735.jpeg?auto=compress&cs=tinysrgb&w=600',
    prompt: 'A playful woman with colorful dyed hair, wearing a headset and holding a game controller, sitting in a room with neon lights, excited expression, photorealistic',
  },
  {
    id: 'gf-7',
    name: 'Mountain Hiker',
    description: 'Adventurous and strong, loves the outdoors.',
    backgroundImageUrl: 'https://images.pexels.com/photos/1674752/pexels-photo-1674752.jpeg?auto=compress&cs=tinysrgb&w=600',
    prompt: 'A strong, adventurous woman with a backpack, standing on a mountain peak with a stunning view, smiling confidently, morning light, photorealistic, high detail',
  },
  {
    id: 'gf-8',
    name: 'Urban Explorer',
    description: 'Chic and modern, knows the city inside out.',
    backgroundImageUrl: 'https://images.pexels.com/photos/3772510/pexels-photo-3772510.jpeg?auto=compress&cs=tinysrgb&w=600',
    prompt: 'A chic woman in a stylish trench coat, walking on a busy city street at night, surrounded by neon signs and reflections on wet pavement, photorealistic',
  },
  {
    id: 'gf-9',
    name: 'Homebody Chef',
    description: 'Warm and caring, a fantastic cook.',
    backgroundImageUrl: 'https://images.pexels.com/photos/4049793/pexels-photo-4049793.jpeg?auto=compress&cs=tinysrgb&w=600',
    prompt: 'A warm, smiling woman wearing an apron, happily cooking in a bright, modern kitchen, surrounded by fresh ingredients, soft natural light, photorealistic',
  },
  {
    id: 'gf-10',
    name: 'Rock Musician',
    description: 'Passionate and intense, with a rebellious spirit.',
    backgroundImageUrl: 'https://images.pexels.com/photos/1674318/pexels-photo-1674318.jpeg?auto=compress&cs=tinysrgb&w=600',
    prompt: 'A passionate female rock musician with dark makeup, playing an electric guitar on a dimly lit stage, intense expression, dramatic stage lighting, photorealistic',
  },
  {
    id: 'gf-11',
    name: 'Yoga Instructor',
    description: 'Calm and centered, promotes peace and wellness.',
    backgroundImageUrl: 'https://images.pexels.com/photos/4056535/pexels-photo-4056535.jpeg?auto=compress&cs=tinysrgb&w=600',
    prompt: 'A serene woman in yoga attire, performing a graceful yoga pose in a tranquil studio with large windows and plants, calm and focused, morning sunlight, photorealistic',
  },
  {
    id: 'gf-12',
    name: 'Mysterious Artist',
    description: 'Enigmatic and creative, sees the world differently.',
    backgroundImageUrl: 'https://images.pexels.com/photos/579474/pexels-photo-579474.jpeg?auto=compress&cs=tinysrgb&w=600',
    prompt: 'An enigmatic woman with a unique hairstyle, in a messy art studio, splattered with paint, looking thoughtfully at a large abstract canvas, moody lighting, photorealistic',
  },
];